### ISSUE TITLE
Bug timeline

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#169]
Il semble que tout les profils ils on ma timeline

![image](https://user-images.githubusercontent.com/44605319/63255374-f04c3880-c275-11e9-84d2-7487229a7979.png)

**Comment by SariTani** [comment]
Toujours le même bug avec un profile crée hier.
La timeline n'est pas personalisée
![image](https://user-images.githubusercontent.com/44605319/67750643-e0985f80-fa2f-11e9-8b47-31067d9e2242.png)

**Comment by yesiman** [comment]
Salut Sari,
Tu peux me dire c'est le profil de qui ?
Je dois mettre en prod ce que j'ai fait sur Dataverse après je rejetterais un oeil sur tout ca.
Bonne journée.

**Comment by SariTani** [comment]
Oui bien sur, 
C'est le profile de Gécica Yogo

Bien à toi!

**Comment by SariTani** [comment]
ok
