### ISSUE TITLE
Ekit - users

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#211]
Sur Ekit users, je ne vois que une liste de 100 utilisateurs alors que les compteurs affichent 143
Je fais comment pour les voir tous? 

Merci!

**Comment by SariTani** [comment]
![image](https://user-images.githubusercontent.com/44605319/70070494-fcc18a80-15f3-11ea-9e5d-04b9143e0219.png)
Lorsque je clique sur Next j'ai cela: 
Il faut revenir en arriere pour voit la totalité de la liste.

![image](https://user-images.githubusercontent.com/44605319/70070444-ec111480-15f3-11ea-871d-3e1b332624c8.png)

Merci!

**Comment by yesiman** [comment]
Mise en ligne correction, a prévoir un bouton pour tout exporter vers excel etintégrer dans ton outil emailing.

**Comment by SariTani** [comment]
👍
