### ISSUE TITLE
Modification des Project sur Ekit prototypes

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#213]
Bonjour Fabrice
j'ai quelques problèmes avec la géolocalisation de certains projets qui sera a modifier, je vois que je n'ai pas la main dessous sur Ekit-prototypes. Comment puis-je modifier leur geoloc?

Merci 
Sari 

![image](https://user-images.githubusercontent.com/44605319/67776279-659b6d00-fa60-11e9-9389-7e82a2f05eeb.png)

**Comment by yesiman** [comment]
Bonjour Sari, Je dois écrire un petit script pour t'ajouter la propriété dans le BO car non prévu initialement, presque fini je met en ligne milieu de semaine !

**Comment by SariTani** [comment]
ok
