### ISSUE TITLE
Affichage des projets sur carto

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#216]
Dans la fiche information des membres (cartographie), on peut voir l'information de la personne et un résumé des projets dont il fait partie.
MAIS on ne vois pas le titre du projet en question, juste la description
![image](https://user-images.githubusercontent.com/44605319/69616963-c3a77a00-1037-11ea-8bb4-dc5108c590fd.png)

**Comment by SariTani** [comment]
![image](https://user-images.githubusercontent.com/44605319/69617049-ea65b080-1037-11ea-804a-45f7c6470514.png)
 vrai titre souligne en jaune

**Comment by yesiman** [comment]
Salut, bizarre donc on n'affichait que le titre avant, pas la présentation du projet ! Je corrige ca et met en test.

**Comment by SariTani** [comment]
Ok de mon côté
