### ISSUE TITLE
Documents adjoints projects

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#217]
Lors de la création d'un projet on peut bien ajouter tout type de document (pdf, mp4, photo, Excel...) 
Par contre lorsque on publie le projet il y a deux bugs

- Le projet n’apparais pas sur la liste des projets, il faut rafraîchir le page pour le voir apparaître

- les Documents n’apparaissent pas dans l'encadré dédié a ce effet
![image](https://user-images.githubusercontent.com/44605319/85832020-9bc7f280-b78f-11ea-99e5-561b06432662.png)

- Si on click sur le icone Pièces jointes on est redirigé vers une page Erreur
"Error: ENOENT: no such file or directory, stat '/var/www/ocp/medias/63af4491-f28b-41b4-87ba-fe387fd277c0.jpg,9688e36d-d447-4061-bcb2-2164fc983061.xlsx,8eff7ce2-179b-408a-f941-76f895997730.pptx,d8a24133-cfc5-4adf-82ff-52e9fdacde2d.m4a,a411e36f-5636-45b5-c7f6-a182c4626753.pdf'"

**Comment by SariTani** [comment]
Ok pour le point 1 et 2 Par contre je ne sais pas si c'est parce que on est sur la page de test mais lorsque je clique sur la pièce jointe je suis envoyé toujours vers une page ERREUR. (Point 3)

"Error: ENOENT: no such file or directory,"

**Comment by yesiman** [comment]
Bonjour Sari,
J'ai répliqué les données de productions (medias) les liens devraient être dorénavant ok.

**Comment by SariTani** [comment]
ok!
