### ISSUE TITLE
[Dashboard] - Widget profile 

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#221]
- L'icône "Projet" n'est pas cliquable  
![image](https://user-images.githubusercontent.com/44605319/88032264-ff023600-cb3d-11ea-9086-e94a7138f266.png)

- Lorsque on veut modifier nos informations personnelles à partir du Dashboard, les modifications ne sont pas sauvegardés au moins que on clique sur le bouton "Enter". Or il m'est arrivé plusieurs fois de cliquer ailleurs dans l'écran et avoir eu l'impression que la modification avait été prise en compte puisque elle reste écrite, par contre lorsque on change de page ou on recharge la page la modification n'a pas été sauvegardé. ça m'as pris du temps pour comprendre qu'il fallait absolument cliquer sur le bouton enter.

**Comment by yesiman** [comment]
Bonjour Sari,
Pour l'icône projets, tu voudrais que lorsque l'on clique cela aille sur l'annuaire ? Ou sur la liste des projets de l'utilisateur ?
Pour la mise à jour dans le dashboard, je vais vérifier normalement cela devrait se sauvegarder sans Enter.
A plus tard.
Fabrice

**Comment by SariTani** [comment]
Pour l'icône projets, se serai plutôt vers la liste des projets de l'utilisateur. Pour moi ce serai: http://test.ocp.ekoal.org/en/profile/5bd8301b75fc9e04007b5387 

Merci!

**Comment by SariTani** [comment]
ok pour les deux points!
