### ISSUE TITLE
[BO] Bug affichage notifications

### ISSUE THREAD

**Issue by MaxLgrs** [yesiman/ekoal.web.ekoalitos.fo.ocp#230]
Quand on clique sur l'icone notification dans le  BO, le tiroir est coupé
![bug affichage notifs](https://user-images.githubusercontent.com/44435658/90492934-05d29780-e142-11ea-8637-75cc5aa58ab3.PNG)

**Comment by SariTani** [comment]
Même bug pour moi. Ça ne le faisait pas la semaine dernière.
