### ISSUE TITLE
Quand on est log out 

### ISSUE THREAD

**Issue by MaxLgrs** [yesiman/ekoal.web.ekoalitos.fo.ocp#236]
- [ ] Je clic sur un membre on me demande de me connecter. On ne peut pas consulter la fiche des acteurs hors connexion

- [ ] Quand je clic sur : forum, news, blogs et projects je retourne à l'accueil
![retour accueil log out](https://user-images.githubusercontent.com/44435658/90500859-c14bf980-e14b-11ea-81ca-d55b5427fee7.PNG)

**Comment by SariTani** [comment]
Ceci est normale, cette information n'est disponible que pour les membres enregistrés.

**Comment by yesiman** [comment]
Je ferme ce ticket
