### ISSUE TITLE
[BO] Option de trie dans Projects

### ISSUE THREAD

**Issue by MaxLgrs** [yesiman/ekoal.web.ekoalitos.fo.ocp#239]
![image](https://user-images.githubusercontent.com/44435658/90611577-38929380-e207-11ea-99b5-4560ce1bf10c.png)
Je pense qu'il faudrait peut-être rajouter une option de trie dans les projets, et peut-être pour news aussi

**Comment by yesiman** [comment]
Modification vers enhancement
