### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#247]
La cartographie n'affiche rien, même p=en faisant une recherche plein texte

**Comment by yesiman** [comment]
Bonjour Sari, J'ai mis une nouvelle version ce matin, peux tu vérifier, si problèmes expliques moi la manipulation exacte que tu fais.
Merci

**Comment by SariTani** [comment]
C'est ok, ça marche maintenant !

**Comment by yesiman** [comment]
Oui j'ai changé pas mal de choses, je finalise le preview sur les news du
dashboard (un peu compliqué) et après normalement on sera bon pou rla mise
en prod !
Bonne soirée
