### ISSUE TITLE
Pieces jointes des news

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#250]
Je ne peut pas gérer les pièces jointes des news, par exemple supprimer cette PJ
![image](https://user-images.githubusercontent.com/44605319/93342719-f5403a80-f82f-11ea-97f8-419a805e398a.png)

dans la partie édition, je ne vois pas les pièces jointes qui sont déjà associées. 

![image](https://user-images.githubusercontent.com/44605319/93342763-038e5680-f830-11ea-9adf-414fa2dbf16e.png)

**Comment by SariTani** [comment]
Cette news n'a pas de pièce jointe mais on voit quand même un encadré dédié à cet effet

![image](https://user-images.githubusercontent.com/44605319/93343552-ea39da00-f830-11ea-8002-4bc8329f4cbf.png)

**Comment by SariTani** [comment]
> Cette news n'a pas de pièce jointe mais on voit quand même un encadré dédié à cet effet
> 
> ![image](https://user-images.githubusercontent.com/44605319/93343552-ea39da00-f830-11ea-8002-4bc8329f4cbf.png)

evidement si on clique dessus on tombe sur un message erreur "Cannot GET /en/event/5f2a747df982ec7a4cb15a84"

**Comment by SariTani** [comment]
certaines liens vers des pages webs n'affichent aucune image alors que d'autres oui

**Comment by yesiman** [comment]
> Cette news n'a pas de pièce jointe mais on voit quand même un encadré dédié à cet effet
> 
> ![image](https://user-images.githubusercontent.com/44605319/93343552-ea39da00-f830-11ea-8002-4bc8329f4cbf.png)

Cela devrait pointer vers une page intermédiaire qui affiche le contenu de l'événement ? Car c'est la news auto généré par la création de l'événement. Donc sinon il ne faut pas que j'ajoute le lien peut être. Je te laisse me dire ce que tu préfères.

**Comment by SariTani** [comment]
vu qu'il y a pas de page proprement dite pour les évènement, on peut ajouté le lien URL a la page web indiqué dans l'évènement si elle existe ? ?

**Comment by yesiman** [comment]
Bonjour Sari,
justement dans la plateforme il n'y a pas de page "evennement", je peux en
créer une qui reprendra les quelques infos de l'event et effectivement cela
permettra au lien d'etre fonctionnel.
A plus tard.
Fabrice

**Comment by SariTani** [comment]
aah moi je parlais du lien url. Tu sais ? dans un évènement on peut associer un lien vers une page web, si il y en a être redirigé vers cette page, si non, ne rien mettre.
T'en penses quoi ?

**Comment by yesiman** [comment]
Ah d'accord donc ce que j'ai fait c'est que lorsque l'on crée un
évènement je crée la news auto mais n'ajoute pas le lien (erreur de ma
part) et cela devrait être ok !
Je teste et je met en ligne !
A plus tard bon début de journée.

**Comment by SariTani** [comment]
> certaines liens vers des pages webs n'affichent aucune image ni TITRE alors que d'autres oui
> ![image](https://user-images.githubusercontent.com/44605319/93343907-53b9e880-f831-11ea-9c82-6da82af726b5.png)

j'ai toujours ce probleme

**Comment by SariTani** [comment]
> Je ne peut pas gérer les pièces jointes des news, par exemple supprimer cette PJ
> ![image](https://user-images.githubusercontent.com/44605319/93342719-f5403a80-f82f-11ea-97f8-419a805e398a.png)
> 
> dans la partie édition, je ne vois pas les pièces jointes qui sont déjà associées.
> 
> ![image](https://user-images.githubusercontent.com/44605319/93342763-038e5680-f830-11ea-9adf-414fa2dbf16e.png)

JE ne peut toujours pas supprimer une pièce jointe

**Comment by yesiman** [comment]
J'ai ajouté un petit preview du doc avec un bouton supprimer pour réaffirmer la zone de saisie afin de modifier la news !

**Comment by SariTani** [comment]
Ok merci!
