### ISSUE TITLE
Dashboard ne charge pas

### ISSUE THREAD

**Issue by SariTani** [yesiman/ekoal.web.ekoalitos.fo.ocp#253]
Les news, bolg et forum ne chargent pas...

![image](https://user-images.githubusercontent.com/44605319/95851476-8e407380-0d52-11eb-8314-bb23d31c274c.png)

**Comment by yesiman** [comment]
Bonjour Sari,
Je viens de tester pas rencontré ce problème.
Peux tu recharge ta page ? Peut être session expirée.
A plus tard.
Fabrice

**Comment by SariTani** [comment]
Je me déconnecté puis reconnecté et effectivement ça marchais!
